// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPGe5DFMwIVwFJam5N8CmODcOsTp5xDNY',
    appId: '1:471924313093:web:5b4e3d84548d83e810606c',
    messagingSenderId: '471924313093',
    projectId: 'brainstationlibrary',
    authDomain: 'brainstationlibrary.firebaseapp.com',
    storageBucket: 'brainstationlibrary.firebasestorage.app',
    measurementId: 'G-2KT952F4Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5EJ553Mds0V7rTZTgCoyRXxiuN8K9_Lg',
    appId: '1:471924313093:android:7690f2563c5acc7210606c',
    messagingSenderId: '471924313093',
    projectId: 'brainstationlibrary',
    storageBucket: 'brainstationlibrary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ4bYrJ4AT-dSbDCPYECZT7PUQHITOlHc',
    appId: '1:471924313093:ios:c8b05657dd034bff10606c',
    messagingSenderId: '471924313093',
    projectId: 'brainstationlibrary',
    storageBucket: 'brainstationlibrary.firebasestorage.app',
    iosBundleId: 'com.example.brainstationLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ4bYrJ4AT-dSbDCPYECZT7PUQHITOlHc',
    appId: '1:471924313093:ios:c8b05657dd034bff10606c',
    messagingSenderId: '471924313093',
    projectId: 'brainstationlibrary',
    storageBucket: 'brainstationlibrary.firebasestorage.app',
    iosBundleId: 'com.example.brainstationLibrary',
  );
}
